version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=universitydb
    ports:
      - "5432:5432"
    volumes:
      - ./universitydb_data:/var/lib/postgresql/data
